name: Deploy Vue Frontend

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Vue application
        run: npm run build

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.VPS_SSH_KEY_B64 }}" | base64 --decode > ~/.ssh/deploy_key

          chmod 600 ~/.ssh/deploy_key

      - name: Add VPS to known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Check SSH key
        shell: bash
        run: |
          chmod 600 ~/.ssh/deploy_key
          echo "SSH key fingerprint:"
          ssh-keygen -lf ~/.ssh/deploy_key

      - name: Test SSH connection
        shell: bash
        run: |
          echo "Testing SSH connection..."
          ssh \
            -vvv \
            -i ~/.ssh/deploy_key \
            -p "${{ secrets.VPS_PORT }}" \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" \
            "echo SSH connection successful"

      - name: Deploy dist to VPS
        shell: bash
        run: |
          rsync -avz \
            --exclude='.well-known/' \
            --exclude='.htaccess' \
            --exclude='.user.ini' \
            -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.VPS_PORT }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no" \
            dist/ \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/www/wwwroot/desadigita.my.id/"